target-version = "py313"
line-length = 120

[lint.isort]
case-sensitive = true
known-first-party = ["django_celery_boost"]

[lint]
select = [
]
ignore = [
  "ALL"
]
preview = true

[lint.pylint]
max-args = 7
max-branches = 14
max-nested-blocks = 8

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.per-file-ignores]
"tests/**.py" = ["S101", "PLR2004", "S", "SIM117", "D", "UP", "PLR0913", "ANN", "N999"]
"src/**/versioning/**.py" = ["N999", ]
"src/**/version.py" = ["ALL", ]
