# Generated by Django 5.1.1 on 2024-10-01 14:20

import concurrency.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlternativeJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number")),
                (
                    "curr_async_result_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Current (active) AsyncResult is",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "last_async_result_id",
                    models.CharField(
                        blank=True, editable=False, help_text="Latest executed AsyncResult is", max_length=36, null=True
                    ),
                ),
                ("celery_history", models.JSONField(blank=True, default=dict, editable=False)),
                ("celery_result", models.CharField(blank=True, default="", editable=False, max_length=100, null=True)),
            ],
            options={
                "permissions": (("test_alternativejob", "Can test AlternativeJob"),),
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "queue", "terminate", "inspect"),
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number")),
                (
                    "curr_async_result_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Current (active) AsyncResult is",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "last_async_result_id",
                    models.CharField(
                        blank=True, editable=False, help_text="Latest executed AsyncResult is", max_length=36, null=True
                    ),
                ),
                ("celery_history", models.JSONField(blank=True, default=dict, editable=False)),
                ("celery_result", models.CharField(blank=True, default="", editable=False, max_length=100, null=True)),
                ("name", models.CharField(max_length=100)),
                ("number", models.IntegerField(default=0)),
                (
                    "op",
                    models.CharField(
                        choices=[("sleep", "sleep"), ("upper", "upper"), ("raise", "raise"), ("progress", "progress")],
                        default="upper",
                        help_text="field to control the implementation of the task",
                        max_length=100,
                    ),
                ),
                ("value", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Job",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "queue", "terminate", "inspect"),
            },
        ),
    ]
