# Generated by Django 4.2.16 on 2024-09-28 06:05

import concurrency.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number")),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                (
                    "curr_async_result_id",
                    models.CharField(blank=True, help_text="Current (active) AsyncResult is", max_length=36, null=True),
                ),
                (
                    "last_async_result_id",
                    models.CharField(blank=True, help_text="Latest executed AsyncResult is", max_length=36, null=True),
                ),
                ("history", models.JSONField(blank=True, default=dict)),
                ("result", models.CharField(blank=True, default="", max_length=100, null=True)),
                ("name", models.CharField(max_length=100)),
                ("number", models.IntegerField(default=0)),
                (
                    "op",
                    models.CharField(
                        choices=[("sleep", "sleep"), ("upper", "upper"), ("raise", "raise")],
                        default="upper",
                        help_text="field to control the implementation of the task",
                        max_length=100,
                    ),
                ),
                ("value", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
